version: '3'

services:
  proxy:
    image: traefik
    container_name: traefik
    command: --web --docker --docker.domain=domain.local --logLevel=DEBUG
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - dmz
      - frontoffice
    labels:
      - "traefik.frontend.rule=Host:traefik.domain.local"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=nextcloud_dmz"

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    depends_on: 
      - mysql_db
    volumes:
      - data:/var/www/html
    networks:
      - backoffice
      - frontoffice
    labels:
      - "traefik.frontend.rule=Host:nextcloud.domain.local"
      - "traefik.backend=nextcloud"
      - "traefik.port=80"
      - "traefik.docker.network=nextcloud_frontoffice"

  mysql_db:
    image: percona/percona-server
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - backoffice
    labels:
      - "traefik.enable=false"

networks:
  dmz:
    driver: bridge
  frontoffice:
    driver: bridge
  backoffice:
    driver: bridge

volumes:
  data:
  db:
